### ISSUE TITLE
Change base profile to reduce logs

### ISSUE THREAD

**Issue by grizzlymannn** [oripka/aa-logprof-py#1]
I started testing this out last night.  Had some minor success with a few of my Docker containers.  I'm trying to generate one for Plex now but I'm running into an issue.  Plex reads so many files on boot that it overflows the audit.log file and the generated profile is hundreds of lines long.

Is there something that I could add to the base profile to stop aa-logprof-py from adding every file in certain directories?

I tried this, but it still picked them up.
`/path/to/dir/** r`

Also, does this script do capabilities, network, etc, or only file access?

**Comment by oripka** [comment]
Hi, I added a command line switch --ignore-dirs (see updated README) in https://github.com/oripka/aa-logprof-py/pull/2. Hope that helps.

**Comment by grizzlymannn** [comment]
Great response, thank you! I'll give it a try later today.

**Comment by grizzlymannn** [comment]
I may be doing something wrong.  When I run this command
`python3 aa-logprof.py --ignore-dirs /usr/share/ca-certificates /var/log/audit/audit.log docker-container`

I get this error
`usage: aa-logprof.py [-h] [--ignore-dirs [IGNORE_DIRS ...]] input_log output_profile
aa-logprof.py: error: the following arguments are required: input_log, output_profile`

**Comment by oripka** [comment]
Yes I see the issue.

For now, put the positional args first

python3 aa-logprof.py /var/log/audit/audit.log docker-container --ignore-dirs /usr/share/ca-certificates

**Comment by oripka** [comment]
Also fixed it in the docs
